# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(760, 560)
        Form.setMinimumSize(QtCore.QSize(760, 560))
        Form.setMaximumSize(QtCore.QSize(760, 560))
        # self.label_name = QtWidgets.QLabel(Form) # 姓名
        # self.label_name.setGeometry(QtCore.QRect(530, 70, 71, 21))
        # self.label_name.setObjectName("label_name")
        # self.label_class = QtWidgets.QLabel(Form) # 班级
        # self.label_class.setGeometry(QtCore.QRect(530, 100, 71, 21))
        # self.label_class.setObjectName("label_class")
        # self.label_id = QtWidgets.QLabel(Form) # 学号
        # self.label_id.setGeometry(QtCore.QRect(530, 40, 71, 21))
        # self.label_id.setObjectName("label_id")
        # self.bt_change_info = QtWidgets.QPushButton(Form)
        # self.bt_change_info.setGeometry(QtCore.QRect(310, 510, 211, 41))
        # self.bt_change_info.setObjectName("bt_change_info")
        self.bt_start_collect = QtWidgets.QPushButton(Form) # 开始采集
        self.bt_start_collect.setGeometry(QtCore.QRect(10, 460, 131, 91))
        self.bt_start_collect.setObjectName("bt_start_collect")
        self.label_title = QtWidgets.QLabel(Form)  # 人脸识别个人信息采集系统
        self.label_title.setGeometry(QtCore.QRect(130, 10, 291, 20))
        self.label_title.setObjectName("label_title")
        # self.bt_check_info = QtWidgets.QPushButton(Form)
        # self.bt_check_info.setGeometry(QtCore.QRect(310, 460, 101, 41))
        # self.bt_check_info.setObjectName("bt_check_info")
        # self.label_sex = QtWidgets.QLabel(Form)  # 性别
        # self.label_sex.setGeometry(QtCore.QRect(530, 130, 71, 21))
        # self.label_sex.setObjectName("label_sex")
        # self.label_birth = QtWidgets.QLabel(Form) # 出生
        # self.label_birth.setGeometry(QtCore.QRect(530, 160, 71, 21))
        # self.label_birth.setObjectName("label_birth")
        self.label_capture = QtWidgets.QLabel(Form)
        self.label_capture.setGeometry(QtCore.QRect(10, 40, 500, 400))
        self.label_capture.setMinimumSize(QtCore.QSize(500, 400))
        self.label_capture.setMaximumSize(QtCore.QSize(500, 400))
        self.label_capture.setText("")
        self.label_capture.setObjectName("label_capture")
        self.bt_take_photo = QtWidgets.QPushButton(Form) # 拍照
        self.bt_take_photo.setGeometry(QtCore.QRect(270, 510, 151, 41))
        self.bt_take_photo.setObjectName("bt_take_photo")
        # self.lineEdit_id = QtWidgets.QLineEdit(Form) # 学号空白框
        # self.lineEdit_id.setGeometry(QtCore.QRect(610, 40, 141, 21))
        # self.lineEdit_id.setObjectName("lineEdit_id")
        # self.lineEdit_name = QtWidgets.QLineEdit(Form) # 名字空白框
        # self.lineEdit_name.setGeometry(QtCore.QRect(610, 70, 141, 21))
        # self.lineEdit_name.setObjectName("lineEdit_name")
        # self.lineEdit_class = QtWidgets.QLineEdit(Form) # 班级空白框
        # self.lineEdit_class.setGeometry(QtCore.QRect(610, 100, 141, 21))
        # self.lineEdit_class.setObjectName("lineEdit_class")
        # self.lineEdit_sex = QtWidgets.QLineEdit(Form)  # 性别空白框
        # self.lineEdit_sex.setGeometry(QtCore.QRect(610, 130, 141, 21))
        # self.lineEdit_sex.setObjectName("lineEdit_sex")
        # self.lineEdit_birth = QtWidgets.QLineEdit(Form)  # 出生空白框
        # self.lineEdit_birth.setGeometry(QtCore.QRect(610, 160, 141, 21))
        # self.lineEdit_birth.setObjectName("lineEdit_birth")
        # self.bt_sure = QtWidgets.QPushButton(Form)  # 确认
        # self.bt_sure.setGeometry(QtCore.QRect(590, 190, 101, 31))
        # self.bt_sure.setObjectName("bt_sure")
        self.tableView = QtWidgets.QTableView(Form) # 查询数据库所有结果框
        self.tableView.setGeometry(QtCore.QRect(530, 30, 221, 441))
        self.tableView.setObjectName("tableView")
        self.lcdNumber_collection_nums = QtWidgets.QLCDNumber(Form) # 已采集数
        self.lcdNumber_collection_nums.setGeometry(QtCore.QRect(430, 470, 71, 31))
        self.lcdNumber_collection_nums.setObjectName("lcdNumber_collection_nums")
        self.label_collected = QtWidgets.QLabel(Form) # 已采集
        self.label_collected.setGeometry(QtCore.QRect(350, 475, 81, 21))
        self.label_collected.setObjectName("label_collected_num")
        self.label_collected_num = QtWidgets.QLabel(Form) # 采集数目
        self.label_collected_num.setGeometry(QtCore.QRect(140, 475, 101, 21))
        self.label_collected_num.setObjectName("label_collected_num")
        self.spinBox_set_num = QtWidgets.QSpinBox(Form) # 采集数设置
        self.spinBox_set_num.setGeometry(QtCore.QRect(250, 471, 81, 31))
        self.spinBox_set_num.setObjectName("spinBox_set_num")
        self.checkBox_auto_collect = QtWidgets.QCheckBox(Form) # 自动采集
        self.checkBox_auto_collect.setGeometry(QtCore.QRect(150, 450, 171, 21))
        self.checkBox_auto_collect.setObjectName("checkBox_auto_collect")
        # self.bt_check_id_faces = QtWidgets.QPushButton(Form)
        # self.bt_check_id_faces.setGeometry(QtCore.QRect(420, 460, 101, 41))
        # self.bt_check_id_faces.setObjectName("bt_check_id_faces")
        self.bt_check_dirs_faces = QtWidgets.QPushButton(Form)
        self.bt_check_dirs_faces.setGeometry(QtCore.QRect(530, 490, 221, 61))
        self.bt_check_dirs_faces.setObjectName("bt_check_dirs_faces")
        # self.label_name.raise_()
        # self.label_class.raise_()
        # self.label_id.raise_()
        self.bt_start_collect.raise_()
        self.label_title.raise_()
        # self.bt_check_info.raise_()
        # self.label_sex.raise_()
        # self.label_birth.raise_()
        # self.bt_change_info.raise_()
        self.label_capture.raise_()
        self.bt_take_photo.raise_()
        # self.bt_sure.raise_()
        # self.lineEdit_id.raise_()
        # self.lineEdit_name.raise_()
        # self.lineEdit_class.raise_()
        # self.lineEdit_sex.raise_()
        # self.lineEdit_birth.raise_()
        self.tableView.raise_()
        self.lcdNumber_collection_nums.raise_()
        self.label_collected.raise_()
        self.label_collected_num.raise_()
        self.spinBox_set_num.raise_()
        self.checkBox_auto_collect.raise_()
        # self.bt_check_id_faces.raise_()
        self.bt_check_dirs_faces.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # Form.setTabOrder控件顺序
        Form.setTabOrder(self.bt_start_collect, self.checkBox_auto_collect)
        Form.setTabOrder(self.checkBox_auto_collect, self.spinBox_set_num)
        Form.setTabOrder(self.spinBox_set_num, self.bt_take_photo)
        Form.setTabOrder(self.bt_take_photo, self.tableView)
        # Form.setTabOrder(self.lineEdit_id, self.lineEdit_name)
        # Form.setTabOrder(self.lineEdit_name, self.lineEdit_class)
        # Form.setTabOrder(self.lineEdit_class, self.lineEdit_sex)
        # Form.setTabOrder(self.lineEdit_sex, self.lineEdit_birth)
        # Form.setTabOrder(self.lineEdit_birth, self.bt_sure)
        # Form.setTabOrder(self.bt_sure, self.tableView)
        # Form.setTabOrder(self.lineEdit_birth, self.bt_check_info)
        # Form.setTabOrder(self.bt_check_info, self.bt_change_info)
        # Form.setTabOrder(self.bt_change_info, self.bt_check_id_faces)
        # Form.setTabOrder(self.bt_check_id_faces, self.tableView)
        Form.setTabOrder(self.tableView, self.bt_check_dirs_faces)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        # self.label_name.setText(_translate("Form", "姓名："))
        # self.label_class.setText(_translate("Form", "班级："))
        # self.label_id.setText(_translate("Form", "学号："))
        # self.label_sex.setText(_translate("Form", "性别："))
        # self.label_birth.setText(_translate("Form", "生日："))
        # self.bt_sure.setText(_translate("Form", "确认"))
        # self.bt_change_info.setText(_translate("Form", "添加或修改信息"))
        self.bt_start_collect.setText(_translate("Form", "开始采集"))
        self.label_title.setText(_translate("Form", "人脸识别个人信息采集系统"))
        # self.bt_check_info.setText(_translate("Form", "查询信息"))
        self.bt_take_photo.setText(_translate("Form", "拍照"))
        self.label_collected.setText(_translate("Form", "已采集"))
        self.label_collected_num.setText(_translate("Form", "采集数目"))
        self.checkBox_auto_collect.setText(_translate("Form", "自动采集"))
        # self.bt_check_id_faces.setText(_translate("Form", "查询人脸数量"))
        self.bt_check_dirs_faces.setText(_translate("Form", "查询所有已采集数据"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
